name: nvidia
description: Beta version of WIPOS with Nvidia

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: 39

modules:
  - from-file: common/common-files.yml
  - from-file: common/common-packages.yml
  - from-file: common/common-flatpaks.yml
  - from-file: common/os-release.yml
  - type: signing