type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
install:
  - onedriver
  - proton-vpn-gnome-desktop